export const initialProjects = [
  {
    id: 'candid-custard-portfolio',
    slug: 'candid-custard-portfolio',
    title: 'Candid Custard Experience',
    client: 'Personal Showcase',
    category: 'Developer Portfolio',
    year: '2026',
    status: 'completed',
    summary: 'A polished portfolio interface with modern layout rhythm and animated presentation.',
    challenge: 'Create a clean personal brand site that still feels interactive and memorable.',
    solution: 'Built focused page flow with subtle motion, clear information hierarchy, and responsive behavior.',
    impact: 'Improved first impression quality and project presentation confidence.',
    tags: ['React', 'UI Design', 'Animation'],
    gradientFrom: '#6ac2ff',
    gradientTo: '#9077ff',
    liveUrl: 'https://candid-custard-f55954.netlify.app/',
    visuals: ['Landing composition', 'Animated section transitions', 'Responsive content layout'],
  },
  {
    id: 'magical-moxie-showcase',
    slug: 'magical-moxie-showcase',
    title: 'Magical Moxie Showcase',
    client: 'Creative Build',
    category: 'Interactive Website',
    year: '2026',
    status: 'completed',
    summary: 'An energetic web experience balancing playful visuals and performance.',
    challenge: 'Maintain visual richness without harming load speed and readability.',
    solution: 'Used lightweight animation patterns and clean component structure for scalable updates.',
    impact: 'Delivered a highly engaging browsing experience with stable responsiveness.',
    tags: ['Frontend', 'Framer Motion', 'UX'],
    gradientFrom: '#40d4bf',
    gradientTo: '#64a2ff',
    liveUrl: 'https://magical-moxie-30e0fd.netlify.app/',
    visuals: ['Immersive hero area', 'Interactive cards', 'Motion-driven storytelling'],
  },
  {
    id: 'golden-raindrop-work',
    slug: 'golden-raindrop-work',
    title: 'Golden Raindrop Project',
    client: 'Concept Release',
    category: 'Frontend Concept',
    year: '2026',
    status: 'completed',
    summary: 'A vivid frontend concept blending elegant structure with smooth interaction design.',
    challenge: 'Ship a premium look while preserving maintainable and readable code.',
    solution: 'Structured reusable sections and polished transitions with mobile-first adjustments.',
    impact: 'Created a portfolio-ready concept suitable for live client demos.',
    tags: ['React', 'Tailwind', 'Responsive'],
    gradientFrom: '#f9aa56',
    gradientTo: '#f06f83',
    liveUrl: 'https://golden-raindrop-0acda1.netlify.app/',
    visuals: ['Premium color direction', 'Interactive layout blocks', 'Refined mobile adaptation'],
  },
  {
    id: 'nebula-control',
    slug: 'nebula-control',
    title: 'Nebula Control',
    client: 'Nebula Systems',
    category: 'SaaS Platform',
    year: '2026',
    status: 'completed',
    summary: 'A cinematic admin platform with real-time monitoring and predictive analytics.',
    challenge:
      'Build a data-heavy interface that remains visually premium while preserving high frame rates.',
    solution:
      'Implemented modular frontend architecture with lazy-loaded routes, motion orchestration, and chart adapters.',
    impact: '42% faster onboarding and 28% higher dashboard engagement.',
    tags: ['React', 'Framer Motion', 'Data Visualization'],
    gradientFrom: '#59b4ff',
    gradientTo: '#7a77ff',
    liveUrl: '',
    visuals: ['Realtime command center', 'AI anomaly alerts', 'Role-based operator panels'],
  },
  {
    id: 'luxe-commerce',
    slug: 'luxe-commerce',
    title: 'Luxe Commerce',
    client: 'Northline Retail',
    category: 'Ecommerce',
    year: '2025',
    status: 'completed',
    summary: 'A premium storefront blending product storytelling with performance-first UX.',
    challenge: 'Balance rich visuals and seamless mobile performance during high-traffic campaigns.',
    solution: 'Introduced predictive asset loading and motion layers optimized for lower-end devices.',
    impact: '31% higher conversion and 2.8x faster route transitions.',
    tags: ['React', 'Tailwind', 'A/B Testing'],
    gradientFrom: '#f98362',
    gradientTo: '#f5c04b',
    liveUrl: '',
    visuals: ['Editorial hero layout', 'Luxury catalog interactions', 'Checkout flow refinement'],
  },
  {
    id: 'arcframe-studio',
    slug: 'arcframe-studio',
    title: 'Arcframe Studio',
    client: 'Arcframe Studio',
    category: 'Agency Website',
    year: '2026',
    status: 'in-progress',
    summary: 'An immersive agency site with layered narratives and scroll-linked 3D transitions.',
    challenge: 'Deliver a visually experimental site without sacrificing maintainability.',
    solution: 'Separated visual systems into reusable modules and introduced a themed component token model.',
    impact: 'In progress with milestone demos reporting strong client feedback.',
    tags: ['Three.js', 'GSAP', 'Component Architecture'],
    gradientFrom: '#2fceb1',
    gradientTo: '#60c7ff',
    liveUrl: '',
    visuals: ['3D art direction', 'Scroll narrative sequencing', 'Motion timing controls'],
  },
]

export const initialEnquiries = [
  {
    id: 'ENQ-2401',
    reference: 'ENQ-2401',
    type: 'project',
    name: 'Ananya Sen',
    email: 'ananya@atlascommerce.io',
    phone: '9876543210',
    company: 'Atlas Commerce',
    service: 'Experience Engineering',
    budget: '$12k - $25k',
    message: 'Looking for a complete redesign of our B2B dashboard.',
    status: 'reviewing',
    createdAt: '2026-03-04',
  },
]

export const initialSectionConfig = {
  hero: true,
  stats: true,
  services: true,
  testimonials: true,
  faq: true,
  clients: true,
}
